### ISSUE TITLE
Issue in taking and train Student data

### ISSUE THREAD

**Issue by umair313** [MidhaTahir/Smart_NEDIANS#4]
**When i click on take Student data i got this error**

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\UMAIR\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "F:/GIT Downloaded/Smart_NEDIANS/Smart_NEDIANS (PROJECT).py", line 312, in <lambda>
    button_3 = Button(frame0,text = " TAKE STUDENT DATA ", bg = 'white', fg = 'RoyalBlue4' , width = 25, height = 1,cursor = 'hand2',command=lambda:open_cam(entry_a.get(),entry_b.get(),entry_c.get()))
TypeError: open_cam() takes 1 positional argument but 3 were given

**When i click on Train Student data i got this error**

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\UMAIR\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "F:/GIT Downloaded/Smart_NEDIANS/Smart_NEDIANS (PROJECT).py", line 175, in training
    faces,ids = getImagesAndLabels('dataset')
  File "F:/GIT Downloaded/Smart_NEDIANS/Smart_NEDIANS (PROJECT).py", line 122, in getImagesAndLabels
    imagePaths = [os.path.join(path,f) for f in os.listdir(path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dataset'

**Comment by umair313** [comment]
> **When i click on take Student data i got this error**
> 
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Users\UMAIR\AppData\Local\Programs\Python\Python37-32\lib\tkinter__init__.py", line 1705, in **call**
> return self.func(*args)
> File "F:/GIT Downloaded/Smart_NEDIANS/Smart_NEDIANS (PROJECT).py", line 312, in
> button_3 = Button(frame0,text = " TAKE STUDENT DATA ", bg = 'white', fg = 'RoyalBlue4' , width = 25, height = 1,cursor = 'hand2',command=lambda:open_cam(entry_a.get(),entry_b.get(),entry_c.get()))
> TypeError: open_cam() takes 1 positional argument but 3 were given
> 
> **When i click on Train Student data i got this error**
> 
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Users\UMAIR\AppData\Local\Programs\Python\Python37-32\lib\tkinter__init__.py", line 1705, in **call**
> return self.func(*args)
> File "F:/GIT Downloaded/Smart_NEDIANS/Smart_NEDIANS (PROJECT).py", line 175, in training
> faces,ids = getImagesAndLabels('dataset')
> File "F:/GIT Downloaded/Smart_NEDIANS/Smart_NEDIANS (PROJECT).py", line 122, in getImagesAndLabels
> imagePaths = [os.path.join(path,f) for f in os.listdir(path)]
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dataset'

**Comment by umair313** [comment]
I imported file in python from jupyter notebook ans run it on Pycharm

**Comment by MidhaTahir** [comment]
please add two additional parameters in open_cam function.
**open_cam(a,b,c):** .
I have also fixed this issue in my code. Thanks for your comment 👍

**Comment by umair313** [comment]
TypeError: open_cam() takes 1 positional argument but 3 were given

open_cam() needs one argument but there is there in code ?
which  to argument must be removed ?

**Comment by MidhaTahir** [comment]
Please download the recent updated file of main project. It will run perfectly.

**Comment by umair313** [comment]
updated .... now when i click  on Take Student Data at this point some time camera window open immediately some time it takes time 2 mint 5 mint and when its open camera window stay still and the blue square that appears on screen gone... and nothing works on .... may be i am running the wrong way as you did not provided instruction how to use it or may be its bug ..
in both cases let me know .... thanks

**Comment by MidhaTahir** [comment]
No! It's absolutely okay , the window that appears will take 50 images as your dataset and then closes (you can check those images in folder "dataset"). Then click on train student data button , it will train your images and a yml file will be created in "trainer" folder. After training click on the marking attendance button and it will then marked your attendance. Thankyou :)
